### ISSUE TITLE
use_frameworks! when I do not use frameworks

### ISSUE THREAD

**Issue by damarte** [firebase/digits-migration-helper-ios#5]
My project is written in Objective C and I do not use frameworks in my podfile. Any alternative to this error?

![image](https://user-images.githubusercontent.com/4304282/27277937-40cfeffa-54e0-11e7-8fcb-119a78acd778.png)

**Comment by ianbarber** [comment]
That's not a frameworks thing, its a modules thing (which is fine in Objective-C), and it looks like the JWT library is missing. Are you installing with Cocoapods?

**Comment by ulukaya** [comment]
use_frameworks tells CocoaPods that you want to use Frameworks instead of Static Libraries. In this project we imported JTW as a module. That's why you need "use_frameworks!' in your podfile regardless if you use objectivec or swift.
IF you are really against it, your other option is to import JWT classes with their header files as in #import "xxx/JTWxxx.h" form.

**Comment by mylyuic** [comment]
@damarte, we just had a new 0.3.0 release which should have addressed your case: you can now use the library without using frameworks.

**Comment by damarte** [comment]
Just in time, thank you very much !!
